// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/battle-net/realms-regions": {
            "get": {
                "description": "Get all the realms and regions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BattleNet"
                ],
                "summary": "Fetch all realms ang regions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RegionRealmResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/character/{region}/{realm}/{character}": {
            "get": {
                "description": "Get summary information about a character",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Character"
                ],
                "summary": "Fetch character profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Region",
                        "name": "region",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Character",
                        "name": "character",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CharacterProfileResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/character/{region}/{realm}/{character}/mounts": {
            "get": {
                "description": "Get mount collection for character",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Character"
                ],
                "summary": "Fetch character mount collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Region",
                        "name": "region",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Realm",
                        "name": "realm",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Character",
                        "name": "character",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "list"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "blizzarddata.BattleNetRegion": {
            "type": "string",
            "enum": [
                "eu",
                "us"
            ],
            "x-enum-varnames": [
                "REGION_EU",
                "REGION_US"
            ]
        },
        "response.CharacterProfileResponse": {
            "type": "object",
            "properties": {
                "faction": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "realm": {
                    "type": "string"
                }
            }
        },
        "response.RealmResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "region": {
                    "$ref": "#/definitions/blizzarddata.BattleNetRegion"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "response.RegionRealmResponse": {
            "type": "object",
            "properties": {
                "realms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RealmResponse"
                    }
                },
                "regions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RegionResponse"
                    }
                }
            }
        },
        "response.RegionResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "$ref": "#/definitions/blizzarddata.BattleNetRegion"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "wowcollector.io",
	Description:      "wowcollector.io API description",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
