definitions:
  blizzarddata.BattleNetRegion:
    enum:
    - eu
    - us
    type: string
    x-enum-varnames:
    - REGION_EU
    - REGION_US
  response.CharacterProfileResponse:
    properties:
      faction:
        type: string
      level:
        type: integer
      name:
        type: string
      realm:
        type: string
    type: object
  response.RealmResponse:
    properties:
      name:
        type: string
      region:
        $ref: '#/definitions/blizzarddata.BattleNetRegion'
      slug:
        type: string
    type: object
  response.RegionRealmResponse:
    properties:
      realms:
        items:
          $ref: '#/definitions/response.RealmResponse'
        type: array
      regions:
        items:
          $ref: '#/definitions/response.RegionResponse'
        type: array
    type: object
  response.RegionResponse:
    properties:
      name:
        type: string
      value:
        $ref: '#/definitions/blizzarddata.BattleNetRegion'
    type: object
host: localhost:8888
info:
  contact: {}
  description: wowcollector.io API description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: wowcollector.io
  version: "1.0"
paths:
  /api/v1/battle-net/realms-regions:
    get:
      description: Get all the realms and regions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RegionRealmResponse'
      summary: Fetch all realms ang regions
      tags:
      - BattleNet
  /api/v1/character/{region}/{realm}/{character}:
    get:
      description: Get summary information about a character
      parameters:
      - description: Region
        in: path
        name: region
        required: true
        type: string
      - description: Realm
        in: path
        name: realm
        required: true
        type: string
      - description: Character
        in: path
        name: character
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CharacterProfileResponse'
      summary: Fetch character profile
      tags:
      - Character
  /api/v1/character/{region}/{realm}/{character}/mounts:
    get:
      description: Get mount collection for character
      parameters:
      - description: Region
        in: path
        name: region
        required: true
        type: string
      - description: Realm
        in: path
        name: realm
        required: true
        type: string
      - description: Character
        in: path
        name: character
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: list
      summary: Fetch character mount collection
      tags:
      - Character
swagger: "2.0"
