definitions:
  blizzarddata.BattleNetRegion:
    enum:
    - eu
    - us
    type: string
    x-enum-varnames:
    - REGION_EU
    - REGION_US
  errorcodes.ErrorCode:
    enum:
    - CHARACTER_NOT_FOUND
    - LOADING_BATTLE_NET_DATA
    - INTERNAL_ERROR
    - NO_DEFAULT_MOUNT_VIEW
    - NO_DEFAULT_TOY_VIEW
    type: string
    x-enum-varnames:
    - CHARACTER_NOT_FOUND
    - LOADING_BATTLE_NET_DATA
    - INTERNAL_ERROR
    - NO_DEFAULT_MOUNT_VIEW
    - NO_DEFAULT_TOY_VIEW
  errorresponse.ErrorResponse:
    properties:
      code:
        $ref: '#/definitions/errorcodes.ErrorCode'
      message:
        type: string
    type: object
  response.AchievementCollectionAchievement:
    properties:
      description:
        type: string
      displayOrder:
        type: integer
      icon:
        type: string
      id:
        type: integer
      isCompleted:
        type: boolean
      name:
        type: string
      points:
        type: integer
    type: object
  response.AchievementCollectionCategorySwagger:
    properties:
      achievements:
        items:
          $ref: '#/definitions/response.AchievementCollectionAchievement'
        type: array
      categories:
        items:
          type: object
        type: array
      displayOrder:
        type: integer
      name:
        type: string
    type: object
  response.CharacterProfileResponse:
    properties:
      faction:
        type: string
      level:
        type: integer
      name:
        type: string
      realm:
        type: string
    type: object
  response.LeaderboardEntry:
    properties:
      character:
        type: string
      count:
        type: integer
      realm:
        type: string
      region:
        type: string
    type: object
  response.MountCollectionCategorySwagger:
    properties:
      categories:
        items:
          type: object
        type: array
      mounts:
        items:
          $ref: '#/definitions/response.MountCollectionMount'
        type: array
      name:
        type: string
      order:
        type: integer
    type: object
  response.MountCollectionMount:
    properties:
      assets:
        $ref: '#/definitions/response.MountCollectionMountAssets'
      description:
        type: string
      id:
        type: integer
      isCollected:
        type: boolean
      name:
        type: string
    type: object
  response.MountCollectionMountAssets:
    properties:
      display:
        type: string
      largeIcon:
        type: string
      smallIcon:
        type: string
    type: object
  response.PaginationResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/response.LeaderboardEntry'
        type: array
      total:
        type: integer
    type: object
  response.PetCollectionCategorySwagger:
    properties:
      categories:
        items:
          type: object
        type: array
      name:
        type: string
      order:
        type: integer
      pets:
        items:
          $ref: '#/definitions/response.PetCollectionPet'
        type: array
    type: object
  response.PetCollectionPet:
    properties:
      assets:
        $ref: '#/definitions/response.PetCollectionPetAssets'
      id:
        type: integer
      isCollected:
        type: boolean
      name:
        type: string
    type: object
  response.PetCollectionPetAssets:
    properties:
      largeIcon:
        type: string
    type: object
  response.RealmResponse:
    properties:
      name:
        type: string
      region:
        $ref: '#/definitions/blizzarddata.BattleNetRegion'
      slug:
        type: string
    type: object
  response.RegionRealmResponse:
    properties:
      realms:
        items:
          $ref: '#/definitions/response.RealmResponse'
        type: array
      regions:
        items:
          $ref: '#/definitions/response.RegionResponse'
        type: array
    type: object
  response.RegionResponse:
    properties:
      name:
        type: string
      value:
        $ref: '#/definitions/blizzarddata.BattleNetRegion'
    type: object
  response.ToyCollectionCategorySwagger:
    properties:
      categories:
        items:
          type: object
        type: array
      name:
        type: string
      order:
        type: integer
      toys:
        items:
          $ref: '#/definitions/response.ToyCollectionToy'
        type: array
    type: object
  response.ToyCollectionToy:
    properties:
      assets:
        $ref: '#/definitions/response.ToyCollectionToyAssets'
      id:
        type: integer
      isCollected:
        type: boolean
      itemId:
        type: integer
      name:
        type: string
    type: object
  response.ToyCollectionToyAssets:
    properties:
      largeIcon:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: wowcollector.io API description
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: wowcollector.io
  version: "1.0"
paths:
  /api/v1/battle-net/realms-regions:
    get:
      description: Get all the realms and regions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RegionRealmResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
      summary: Fetch all realms ang regions
      tags:
      - BattleNet
  /api/v1/character/{region}/{realm}/{character}:
    get:
      description: Get summary information about a character
      parameters:
      - description: Region
        in: path
        name: region
        required: true
        type: string
      - description: Realm
        in: path
        name: realm
        required: true
        type: string
      - description: Character
        in: path
        name: character
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CharacterProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
      summary: Fetch character profile
      tags:
      - Character
  /api/v1/character/{region}/{realm}/{character}/achievements:
    get:
      description: Get achievement collection for character
      parameters:
      - description: Region
        in: path
        name: region
        required: true
        type: string
      - description: Realm
        in: path
        name: realm
        required: true
        type: string
      - description: Character
        in: path
        name: character
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.AchievementCollectionCategorySwagger'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
      summary: Fetch character achievement collection
      tags:
      - Character
  /api/v1/character/{region}/{realm}/{character}/mounts:
    get:
      description: Get mount collection for character
      parameters:
      - description: Region
        in: path
        name: region
        required: true
        type: string
      - description: Realm
        in: path
        name: realm
        required: true
        type: string
      - description: Character
        in: path
        name: character
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.MountCollectionCategorySwagger'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
      summary: Fetch character mount collection
      tags:
      - Character
  /api/v1/character/{region}/{realm}/{character}/pets:
    get:
      description: Get pet collection for character
      parameters:
      - description: Region
        in: path
        name: region
        required: true
        type: string
      - description: Realm
        in: path
        name: realm
        required: true
        type: string
      - description: Character
        in: path
        name: character
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.PetCollectionCategorySwagger'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
      summary: Fetch character pet collection
      tags:
      - Character
  /api/v1/character/{region}/{realm}/{character}/toys:
    get:
      description: Get toy collection for character
      parameters:
      - description: Region
        in: path
        name: region
        required: true
        type: string
      - description: Realm
        in: path
        name: realm
        required: true
        type: string
      - description: Character
        in: path
        name: character
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.ToyCollectionCategorySwagger'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
      summary: Fetch character toy collection
      tags:
      - Character
  /api/v1/leaderboard/mounts:
    get:
      description: Get the leaderboard mounts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PaginationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorresponse.ErrorResponse'
      summary: Fetch leaderboard for mounts
      tags:
      - BattleNet
swagger: "2.0"
