apiVersion: v1
stringData:
  clientId: {{clientId}}
  secret: {{secret}}
  scannerClientId: {{scannerClientId}}
  scannerSecret: {{scannerSecret}}
  discordClientId: "{{discordClientId}}"
kind: Secret
metadata:
  creationTimestamp: null
  name: wowcollector-staging-credentials
  namespace: wowcollector