apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mongo-staging
  name: mongo-staging
  namespace: wowcollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo-staging
  strategy: { }
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo-staging
    spec:
      containers:
        - image: mongo
          name: mongo-staging
          livenessProbe: null
          readinessProbe: null
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-staging-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-staging-creds
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mongo-staging
  name: mongo-staging
  namespace: wowcollector
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app.kubernetes.io/name: mongo-staging