apiVersion: v1
stringData:
  username: admin
  password: {{password}}
  connection: mongodb://admin:{{password}}@mongo-staging:27017/admin
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo-staging-creds
  namespace: wowcollector