<script lang="ts" setup>
import { Icons } from '~/constants';

definePageMeta({
  layout: 'empty',
});

const router = useRouter();
</script>

<template>
  <div class="max-w-4xl mx-auto px-4 py-8">
    <UButton
      class="mb-4"
      variant="ghost"
      :icon="Icons.BACK"
      @click="router.back()"
    >
      Go back</UButton
    >

    <h1 class="text-3xl font-bold mb-6">Privacy Policy</h1>
    <p class="text-sm text-gray-500 mb-8">Last updated: September 02, 2024</p>

    <p class="mb-6">
      This Privacy Policy describes Our policies and procedures on the
      collection, use and disclosure of Your information when You use the
      Service and tells You about Your privacy rights and how the law protects
      You.
    </p>
    <p class="mb-8">
      We use Your Personal data to provide and improve the Service. By using the
      Service, You agree to the collection and use of information in accordance
      with this Privacy Policy.
    </p>

    <h2 class="text-2xl font-semibold mb-4">Interpretation and Definitions</h2>
    <h3 class="text-xl font-semibold mb-2">Interpretation</h3>
    <p class="mb-6">
      The words of which the initial letter is capitalized have meanings defined
      under the following conditions. The following definitions shall have the
      same meaning regardless of whether they appear in singular or in plural.
    </p>

    <h3 class="text-xl font-semibold mb-2">Definitions</h3>
    <ul class="list-disc pl-6 mb-8 space-y-2">
      <li>
        <strong>Account</strong> means a unique account created for You to
        access our Service or parts of our Service.
      </li>
      <li>
        <strong>Affiliate</strong> means an entity that controls, is controlled
        by or is under common control with a party...
      </li>
      <li>
        <strong>Company</strong> (referred to as either "the Company", "We",
        "Us" or "Our" in this Agreement) refers to wowcollector.
      </li>
      <li>
        <strong>Cookies</strong> are small files that are placed on Your
        computer, mobile device or any other device...
      </li>
      <li><strong>Country</strong> refers to: Sweden</li>
      <li>
        <strong>Device</strong> means any device that can access the Service
        such as a computer, a cellphone or a digital tablet.
      </li>
      <li>
        <strong>Personal Data</strong> is any information that relates to an
        identified or identifiable individual.
      </li>
      <li><strong>Service</strong> refers to the Website.</li>
      <li>
        <strong>Third-party Social Media Service</strong> refers to any website
        or any social network website through which a User can log in or create
        an account to use the Service.
      </li>
      <li>
        <strong>Usage Data</strong> refers to data collected automatically,
        either generated by the use of the Service or from the Service
        infrastructure itself (for example, the duration of a page visit).
      </li>
      <li>
        <strong>Website</strong> refers to wowcollector, accessible from
        https://wowcollector.io/
      </li>
      <li>
        <strong>You</strong> means the individual accessing or using the
        Service, or the company, or other legal entity on behalf of which such
        individual is accessing or using the Service, as applicable.
      </li>
    </ul>

    <h2 class="text-2xl font-semibold mb-4">
      Collecting and Using Your Personal Data
    </h2>
    <h3 class="text-xl font-semibold mb-2">Types of Data Collected</h3>
    <h4 class="text-lg font-semibold mb-2">Personal Data</h4>
    <p class="mb-6">
      While using Our Service, We may ask You to provide Us with certain
      personally identifiable information that can be used to contact or
      identify You. This is and will in most cases be completely optional.
    </p>

    <h4 class="text-lg font-semibold mb-2">Usage Data</h4>
    <p class="mb-6">
      Usage Data may include information such as Your Device's Internet Protocol
      address (e.g. IP address), browser type, browser version, the pages of our
      Service that You visit, the time and date of Your visit, the time spent on
      those pages, unique device identifiers and other diagnostic data.
    </p>

    <h3 class="text-xl font-semibold mb-2">
      Information from Third-Party Social Media Services
    </h3>
    <p class="mb-6">
      The Company allows You to log in to use the Service through the following
      Third-party Providers:
    </p>
    <ul class="list-disc pl-6 mb-8 space-y-2">
      <li>Battle.net</li>
      <li>Discord</li>
    </ul>

    <h3 class="text-xl font-semibold mb-2">
      Tracking Technologies and Cookies
    </h3>
    <p class="mb-6">
      We use Cookies and similar tracking technologies to track the activity on
      Our Service and store certain information. Tracking technologies used are
      beacons, tags, and scripts to collect and track information and to improve
      and analyze Our Service.
    </p>

    <h2 class="text-2xl font-semibold mb-4">Use of Your Personal Data</h2>
    <ul class="list-disc pl-6 mb-8 space-y-2">
      <li>
        We only collect necessary data to provide you with a more rich
        experience on the website.
      </li>
    </ul>

    <h2 class="text-2xl font-semibold mb-4">Retention of Your Personal Data</h2>
    <p class="mb-6">
      The Company will retain Your Personal Data only for as long as is
      necessary for the purposes set out in this Privacy Policy. We will retain
      and use Your Personal Data to the extent necessary to comply with our
      legal obligations, resolve disputes, and enforce our legal agreements and
      policies.
    </p>
    <p class="mb-8">
      The Company will also retain Usage Data for internal analysis purposes.
      Usage Data is generally retained for a shorter period, except when this
      data is used to strengthen the security or to improve the functionality of
      Our Service, or We are legally obligated to retain this data for longer
      periods.
    </p>

    <h2 class="text-2xl font-semibold mb-4">Security of Your Personal Data</h2>
    <p class="mb-8">
      The security of Your Personal Data is important to Us, but remember that
      no method of transmission over the Internet, or method of electronic
      storage is 100% secure. While We strive to use commercially acceptable
      means to protect Your Personal Data, We cannot guarantee its absolute
      security.
    </p>

    <h2 class="text-2xl font-semibold mb-4">Links to Other Websites</h2>
    <p class="mb-8">
      Our Service may contain links to other websites that are not operated by
      Us. If You click on a third party link, You will be directed to that third
      party's site. We strongly advise You to review the Privacy Policy of every
      site You visit. We have no control over and assume no responsibility for
      the content, privacy policies or practices of any third party sites or
      services.
    </p>

    <h2 class="text-2xl font-semibold mb-4">Changes to this Privacy Policy</h2>
    <p class="mb-8">
      We may update Our Privacy Policy from time to time. We will notify You of
      any changes by posting the new Privacy Policy on this page. We will let
      You know via email and/or a prominent notice on Our Service, prior to the
      change becoming effective and update the "Last updated" date at the top of
      this Privacy Policy.
    </p>

    <div class="w-full">
      <UButton variant="ghost" :icon="Icons.BACK" @click="router.back()">
        Go back
      </UButton>
    </div>
  </div>
</template>
