name: Pull request

on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git fetch origin +refs/heads/develop:refs/remotes/origin/develop

      - name: Check that changelog is updated
        id: check-changelog
        run: |
          git fetch origin develop

          new_files=$(git diff --name-status origin/develop...HEAD | grep '^A' | awk '{print $2}' | grep '^front-end/changelog/current/')

          if [ -z "$new_files" ]; then
            echo "No new files found in front-end/changelog/current."
            exit 1
          else
            echo "New files found in front-end/changelog/current:"
            echo "$new_files"
          fi