name: Release Version

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'The type of release: major, minor, patch'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Read current version
      id: read_version
      run: echo "current_version=$(cat version.txt)" >> $GITHUB_ENV

    - name: Update version based on release type
      id: update_version
      run: bash scripts/update-version.sh

    - name: Create release folder
      id: create_release_folder
      run: |
        new_version="${{ env.new_version }}"
        timestamp=$(date +%s)
        release_folder="changelog/releases/${new_version}-${timestamp}"
        mkdir -p "$release_folder"
        echo "release_folder=$release_folder" >> $GITHUB_ENV

    - name: Move JSON files to release folder
      run: |
        mv changelog/current/*.json "${{ env.release_folder }}/"

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add version.txt changelog/releases/
        git commit -m "Release ${{ env.new_version }}"
        git push origin main

    - name: Create a new tag
      run: |
        git tag "release-${{ env.new_version }}"
        git push origin "release-${{ env.new_version }}"
